# Make sure to check the documentation at http://goreleaser.com
# This is an example goreleaser.yaml file with some sane defaults.
version: 2

# Override detected git repository
git:
  tag_sort: -version:refname

github_urls:
  download: https://github.com

release:
  github:
    owner: peauc
    name: lazydocker-ng

env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto

builds:
  - id: binary
    goos:
      # - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease

archives:
  - id: binary
    ids:
      - binary
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}x86
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    files:
      - none*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bump"

homebrew_casks:
  - repository:
      owner: peauc
      name: homebrew-lazydocker-ng

    homepage: "https://github.com/peauc/lazydocker-ng/"
    description: "The continuation of lazydocker the simple terminal UI for docker, written in Go"

# AUR (Arch User Repository) configuration
aurs:
  - name: lazydocker-ng-bin
    homepage: "https://github.com/peauc/lazydocker-ng/"
    git_url: "ssh://aur@aur.archlinux.org/lazydocker-ng-bin.git"
    description: "The continuation of lazydocker the simple terminal UI for docker, written in Go"
    maintainers:
      - "Clément PÉAU <clement dot peau at gmail dot com>"
    license: "MIT"

    private_key: "{{ .Env.AUR_KEY }}"
    commit_msg_template: "Update to {{ .Tag }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
